### ISSUE TITLE
Cannot Start Application

### ISSUE THREAD

**Issue by icefiresr** [jshackles/idle_master#106]
Hi there,

once I start the app (hit the setup.exe) I will get the following error:

Cannot Start Application. The application is improperly formatted. Contact the application vendor for assistance.

Details from the error:
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.1022
	System.Deployment.dll 		: 4.0.30319.1 (RTMRel.030319-0100)
	clr.dll 			: 4.0.30319.1022 (RTMGDR.030319-1000)
	dfdll.dll 			: 4.0.30319.1 (RTMRel.030319-0100)
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

SOURCES
	Deployment url			: http://steamidlemaster.com/install/IdleMaster.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://steamidlemaster.com/install/IdleMaster.application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from http://steamidlemaster.com/install/IdleMaster.application: the manifest may not be valid or the file could not be opened.
		+ Manifest XML signature is not valid.
		+ SignatureDescription could not be created for the signature algorithm supplied.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [4/1/2015 10:58:43 AM] : Activation of http://steamidlemaster.com/install/IdleMaster.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [4/1/2015 10:58:56 AM] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from http://steamidlemaster.com/install/IdleMaster.application: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (SignatureValidation)
		- Manifest XML signature is not valid.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Security.Cryptography.CryptographicException
		- SignatureDescription could not be created for the signature algorithm supplied.
		- Source: System.Security
		- Stack trace:
			at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
			at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
			at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
			at System.Deployment.Internal.CodeSigning.SignedCmiManifest.Verify(CmiManifestVerifyFlags verifyFlags)
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by CorruptComputer** [comment]
Just use the portable version if the installer doesn't work.
