### ISSUE TITLE
Badge page didn't load

### ISSUE THREAD

**Issue by Vyious** [jshackles/idle_master#188]
Hello, 

I started having this issue recently where after i login with my steam account it goes into a loop of trying to load the badge page but it doesn't work 

so i took the liberty to fiddle around with the code and i came up with this log:

System.Net.WebException: An exception occurred during a WebClient request. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.WebClient.DownloadBitsState.SetResponse(WebResponse response)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IdleMaster.CookieClient.<GetHttpAsync>d__5.MoveNext() in c:\Users\"Location"\Source\IdleMaster\CookieClient.cs:line 90

And i found out that if i replace the URL for my steam profile which is something like that : 

http://steamcommunity.com/profiles/496456465645/badges/?p=1

with my actual username that i see in the browser URL bar which looks like this:

http://steamcommunity.com/profiles/"NAME"/badges/?p=1

IM is happy and idling again.

Regards.

**Comment by Genetai** [comment]
I have the exact same problem even though things worked fine before (problem since last couple/2 days?). 

Idle Master keeps trying, and sometimes succeeds, but it always ends in me no longer being signed in and unable to idle. When it does work I can click the "Update game status" for a refresh and it will still work then but when I restart (instead of just "refreshing") the badge page won't load again. Oh, and when I restart my signed in session is saved just fine so I don't know what triggers the session to be reset when I leave Idle Master retrying to connect to the badge page for a long while. 

![idlemaster_151110](https://cloud.githubusercontent.com/assets/9928966/11069296/b3d821ae-87d5-11e5-9dc2-a88c6bbab48c.png)
![idlemaster_151110_2](https://cloud.githubusercontent.com/assets/9928966/11069298/b64ab2f8-87d5-11e5-8312-c367b67e243c.png)
![idlemaster_151110_3](https://cloud.githubusercontent.com/assets/9928966/11069299/b7efb194-87d5-11e5-9691-63866074c8f4.png)

Please look into this.

```
10-11-2015 11:47:56   CookieClient -> GetHttpAsync, for url = http://steamcommunity.com/profiles/{LONGNUMBER}/badges/?p=1
System.Net.WebException: An exception occurred during a WebClient request. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.WebClient.DownloadBitsState.SetResponse(WebResponse response)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IdleMaster.CookieClient.<GetHttpAsync>d__5.MoveNext()
```

**Comment by ardaozkal** [comment]
>http://steamcommunity.com/profiles/"NAME"/badges/?p=1

Did you mean http://steamcommunity.com/id/name/badges/?p=1 ?

Also I think that there might be a code that tries to keep the address on "http://steamcommunity.com/profiles/76561198034299068/badges/?p=1" rather than "http://steamcommunity.com/id/ardaozkal/badges?p=1" which steam redirects to.

**Comment by Vyious** [comment]
Yes you're URL is correct excuse me i missed the "id" 
http://steamcommunity.com/id/name/badges/?p=1 ?

**Comment by Tsunamical** [comment]
Fixed by #197

**Comment by yashendra2797** [comment]
Well I'm facing this problem too. Running the latest IM downloaded from the website

**Comment by Genetai** [comment]
I just wanted to add that as of 1.4.0.0 this has been fixed for me and everything is still working fine. So Yashendra2797 make sure that it's actually 1.4.0.0 that is running and it should be fine.

**Comment by yashendra2797** [comment]
@genetal Yup. Latest IM (1.4.0.0) and latest stable Steam. Tried on my old Windows 8 laptop as well as a Parallels Virtual Machine running Windows 10 on my Macbook Air Mid 2013.

**Comment by bruceweed** [comment]
Yea not working for me either. just keeps saying it can't load the badge page ect. Tried everything and got nowhere. Wonder if steam got wise..... ppftttt hahaha naw probably something simple. Im going to see if I can't figure it out while I wait for a response if I fix the issue I'll let everyone know what I did to fix it myself.

**Comment by bruceweed** [comment]
Alright at the moment. I believe this to be an issue on steams end perhaps? I see them having a little issue here atm. Unless it is my internet connection (HIGHLY unlikely), however, you never know.

**Comment by bruceweed** [comment]
I can see the badge page and everything. It appears as if it isn't giving it enough time to collect everything before it times out. Got to remember, there are people out there that have literally THOUSANDS of games.

**Comment by DisenzZ** [comment]
Hello! I just fixed mine by downloading the new update. You can find it here: http://www.steamidlemaster.com/ Please tell me if this worked for you to

**Comment by bruceweed** [comment]
using a different script now that offers more options

**Comment by CherryPill** [comment]
@DisenzZ Works for me now.
