### ISSUE TITLE
Badge page didn't load

### ISSUE THREAD

**Issue by Tujurikkuja** [jshackles/idle_master#241]
There seems to be an error while loading the badges page.

This is in the error log:

04.01.2017 10:16.28   CookieClient -> GetHttpAsync, for url = http://steamcommunity.com/profiles/<profile_no>/badges/?p=1
System.Net.WebException: An exception occurred during a WebClient request. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.WebClient.DownloadBitsState.SetResponse(WebResponse response)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IdleMaster.CookieClient.<GetHttpAsync>d__5.MoveNext()

I tried opening the URL in the browser and it works so it seems like something is broken in the successful load handle.

Would greatly appreciate a fix for that. Big time fan :)

**Comment by goto1134** [comment]
same problem here

**Comment by Tujurikkuja** [comment]
But it seems like the owner has abandoned the project so I guess there's no hope for a fix. Unless someone forks it and takes over the development/maintenance.

**Comment by goto1134** [comment]
Fixed by #197

**Comment by Tujurikkuja** [comment]
Do I really have to open this in VS? Is there a simpler way to modify the Setup so that it would load the binaries from this fork?

**Comment by goto1134** [comment]
@Tujurikkuja no, but you can get it from my dropbox fixed. https://www.dropbox.com/s/uk08zao9giwqq5m/idle_master.zip?dl=0

**Comment by Tujurikkuja** [comment]
Already loaded another branch from user treloret. His fix seemed more reasonable (not looping over all the cookies).

**Comment by goto1134** [comment]
@Tujurikkuja link it here please

**Comment by Tujurikkuja** [comment]
https://github.com/jshackles/idle_master/pull/243

**Comment by opello** [comment]
I don't think iterating the collection twice (once for each item lookup) is more reasonable.
