### ISSUE TITLE
Badge page didn't load

### ISSUE THREAD

**Issue by tw0f1sh** [jshackles/idle_master#291]
since some days i got the error loop "Badge page didn't load". Set the privacy from my profile to public didnt help. Profile URL is correct, i just censored it

here the error log:
``08.05.2018 08:28:18   Badge -> LoadBadgesAsync, for profile = http://steamcommunity.com/profiles/7656119xxxxxxxx
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmMain.ProcessBadgesOnPage(HtmlDocument document)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__23.MoveNext()
08.05.2018 08:28:28   Badge -> LoadBadgesAsync, for profile = http://steamcommunity.com/profiles/7656119xxxxxxxx
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmMain.ProcessBadgesOnPage(HtmlDocument document)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__23.MoveNext()

**Comment by Amorano** [comment]
Same result. No longer works.

5/9/2018 9:48:29 AM   Badge -> LoadBadgesAsync, for profile = http://steamcommunity.com/profiles/76561198027397440
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmMain.ProcessBadgesOnPage(HtmlDocument document)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__23.MoveNext()
5/9/2018 9:48:40 AM   Badge -> LoadBadgesAsync, for profile = http://steamcommunity.com/profiles/76561198027397440
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmMain.ProcessBadgesOnPage(HtmlDocument document)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__23.MoveNext()
5/9/2018 9:48:50 AM   Badge -> LoadBadgesAsync, for profile = http://steamcommunity.com/profiles/76561198027397440
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmMain.ProcessBadgesOnPage(HtmlDocument document)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__23.MoveNext()
5/9/2018 9:49:01 AM   Badge -> LoadBadgesAsync, for profile = http://steamcommunity.com/profiles/76561198027397440
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmMain.ProcessBadgesOnPage(HtmlDocument document)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__23.MoveNext()
5/9/2018 9:49:12 AM   Badge -> LoadBadgesAsync, for profile = http://steamcommunity.com/profiles/76561198027397440
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmMain.ProcessBadgesOnPage(HtmlDocument document)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__23.MoveNext()
5/9/2018 9:49:22 AM   Badge -> LoadBadgesAsync, for profile = http://steamcommunity.com/profiles/76561198027397440
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmMain.ProcessBadgesOnPage(HtmlDocument document)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__23.MoveNext()

**Comment by jonas-med-ett-s** [comment]
You can try to update Steamworks.NET, it seems to help with certain issues. 

I have bundled the latest version of Steamworks.NET with my own fork of Idle Master, feel free to try it out: https://github.com/JonasNilson/idle_master_extended/releases

**Comment by whispercodeDev** [comment]
@JonasNilson 
Cool, thank you - I already thought that I do something wrong..

**Comment by GottZ** [comment]
small hint: could it be that some people use the current steam client beta?
it also changes parts of the steamcommunity itself.

**Comment by jonas-med-ett-s** [comment]
> could it be that some people use the current steam client beta? @GottZ 

Idle Master parses data from the web version of Steam. At this moment the badge page is unaffected by the Steam community updates - but that could change in a near future.
