### ISSUE TITLE
Cannot Install idle master winxp prof 32bit

### ISSUE THREAD

**Issue by bowekr** [jshackles/idle_master#71]
open setup.exe then this error message log
```
PLATFORM VERSION INFO
	Windows 			: 5.1.2600.196608 (Win32NT)
	Common Language Runtime 	: 4.0.30319.1
	System.Deployment.dll 		: 4.0.30319.1 (RTMRel.030319-0100)
	clr.dll 			: 4.0.30319.1 (RTMRel.030319-0100)
	dfdll.dll 			: 4.0.30319.1 (RTMRel.030319-0100)
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

SOURCES
	Deployment url			: http://www.steamidlemaster.com/install/IdleMaster.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://www.steamidlemaster.com/install/IdleMaster.application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from http://www.steamidlemaster.com/install/IdleMaster.application: the manifest may not be valid or the file could not be opened.
		+ Manifest XML signature is not valid.
		+ SignatureDescription could not be created for the signature algorithm supplied.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [1/1/2015 6:01:16 PM] : Activation of http://www.steamidlemaster.com/install/IdleMaster.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [1/1/2015 6:01:20 PM] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from http://www.steamidlemaster.com/install/IdleMaster.application: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (SignatureValidation)
		- Manifest XML signature is not valid.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Security.Cryptography.CryptographicException
		- SignatureDescription could not be created for the signature algorithm supplied.
		- Source: System.Security
		- Stack trace:
			at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
			at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
			at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
			at System.Deployment.Internal.CodeSigning.SignedCmiManifest.Verify(CmiManifestVerifyFlags verifyFlags)
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

```

**Comment by jshackles** [comment]
Windows XP is not supported with the latest version of Idle Master as it has been created using the .NET Framework 4.5 which is not available on that platform.

The old Python version of Idle Master should work fine with Windows XP, it can be found here: https://github.com/jshackles/idle_master/tree/92e5e939376ff7abdcb99139823bc2bd2b98700c
