### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by RasRom** [jshackles/idle_master#74]
Hi jshackles. I downloaded your program and when I run this setup it says "Cannot continue. The application is improperly formatted. Contact the application vendor for assistance." And here are the details:

	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.1026
	System.Deployment.dll 		: 4.0.30319.1029 (RTMGDR.030319-1000)
	clr.dll 			: 4.0.30319.1026 (RTMGDR.030319-1000)
	dfdll.dll 			: 4.0.30319.1029 (RTMGDR.030319-1000)
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

SOURCES
	Deployment url			: http://steamidlemaster.com/install/IdleMaster.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://steamidlemaster.com/install/IdleMaster.application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from http://steamidlemaster.com/install/IdleMaster.application: the manifest may not be valid or the file could not be opened.
		+ Manifest XML signature is not valid.
		+ SignatureDescription could not be created for the signature algorithm supplied.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [2.1.2015 18:17:31] : Activation of http://steamidlemaster.com/install/IdleMaster.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2.1.2015 18:17:31] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from http://steamidlemaster.com/install/IdleMaster.application: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (SignatureValidation)
		- Manifest XML signature is not valid.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Security.Cryptography.CryptographicException
		- SignatureDescription could not be created for the signature algorithm supplied.
		- Source: System.Security
		- Stack trace:
			at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
			at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
			at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
			at System.Deployment.Internal.CodeSigning.SignedCmiManifest.Verify(CmiManifestVerifyFlags verifyFlags)
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

I would be very happy if you could help me. Thanks and I appreciate your work

-RasRom

**Comment by ajs** [comment]
Looks like OP is running Vista. So am I (on my living room system, which is not my primary gaming machine). Wonder if that's the issue...

**Comment by gamemaster1494** [comment]
Try downloading the zip from here and running the setup inside the zip. Maybe that will fix it.

**Comment by Fikoblin** [comment]
Reinstalling .Net Framework should help. Here is a link: http://www.microsoft.com/en-us/download/details.aspx?id=30653

**Comment by RasRom** [comment]
I'm not running Vista but reinstalling .Net Framework worked. Thanks alot guys! :)
