### ISSUE TITLE
Cannot Start Application

### ISSUE THREAD

**Issue by Labogani** [jshackles/idle_master#89]
PLATFORM VERSION INFO
	Windows 			: 6.2.9200.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.34014
	System.Deployment.dll 		: 4.0.30319.34243 built by: FX452RTMGDR
	clr.dll 			: 4.0.30319.34014 built by: FX45W81RTMGDR
	dfdll.dll 			: 4.0.30319.34243 built by: FX452RTMGDR
	dfshim.dll 			: 6.3.9600.16384 (winblue_rtm.130821-1623)

SOURCES
	Deployment url			: http://www.steamidlemaster.com/install/IdleMaster.application
						Server		: Apache/2.2.22 (Debian)

IDENTITIES
	Deployment Identity		: IdleMaster.application, Version=0.7.0.12, Culture=neutral, PublicKeyToken=2608479b42bdf612, processorArchitecture=x86

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://www.steamidlemaster.com/install/IdleMaster.application resulted in exception. Following failure messages were detected:
		+ Exception occurred during store operation.
		+ Value does not fall within the expected range.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [30/01/2015 19:51:48] : Activation of http://www.steamidlemaster.com/install/IdleMaster.application has started.
	* [30/01/2015 19:51:49] : Processing of deployment manifest has successfully completed.

ERROR DETAILS
	Following errors were detected during this operation.
	* [30/01/2015 19:51:49] System.Deployment.Application.DeploymentException (ComponentStore)
		- Exception occurred during store operation.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)
			at System.Deployment.Application.ComponentStore.SetPendingDeployment(SubscriptionState subState, DefinitionIdentity deployId, DateTime checkTime)
			at System.Deployment.Application.SubscriptionStore.SetLastCheckTimeToNow(SubscriptionState subState)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.ArgumentException
		- Value does not fall within the expected range.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.Transact(IntPtr cOperation, StoreTransactionOperation[] rgOperations, UInt32[] rgDispositions, Int32[] rgResults)
			at System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)

COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [30/01/2015 19:51:49]

**Comment by jshackles** [comment]
Try downloading the "portable version" from www.SteamIdleMaster.com, as it will bypass this installation error entirely.
